function tableout = importPixelsID(workbookFile,sheetName,startRow,endRow)
%IMPORTFILE Import data from a spreadsheet
%   DATA = IMPORTFILE(FILE) reads data from the first worksheet in the
%   Microsoft Excel spreadsheet file named FILE and returns the data as a
%   table.
%
%   DATA = IMPORTFILE(FILE,SHEET) reads from the specified worksheet.
%
%   DATA = IMPORTFILE(FILE,SHEET,STARTROW,ENDROW) reads from the specified
%   worksheet for the specified row interval(s). Specify STARTROW and
%   ENDROW as a pair of scalars or vectors of matching size for
%   dis-contiguous row intervals. To read to the end of the file specify an
%   ENDROW of inf.
%
%	Non-numeric cells are replaced with: NaN
%
% Example:
%   PIxelsID = importfile('PIxels_ID.xlsx','Feuil1',2,119);
%
%   See also XLSREAD.

% Auto-generated by MATLAB on 2017/01/31 16:11:58

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 3
    startRow = 2;
    endRow = 121;
end

%% Import the data
[~, ~, raw] = xlsread(workbookFile, sheetName, sprintf('A%d:O%d',startRow(1),endRow(1)));
for block=2:length(startRow)
    [~, ~, tmpRawBlock] = xlsread(workbookFile, sheetName, sprintf('A%d:O%d',startRow(block),endRow(block)));
    raw = [raw;tmpRawBlock]; %#ok<AGROW>
end
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
cellVectors = raw(:,[2,15]);
raw = raw(:,[1,3,4,5,6,7,8,9,10,11,12,13,14]);

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
I = cellfun(@(x) ischar(x), raw);
raw(I) = {NaN};
data = reshape([raw{:}],size(raw));

%% Create table
tableout = table;

%% Allocate imported array to column variable names
tableout.NUMERO = data(:,1);
tableout.ConfName = cellVectors(:,1);
tableout.MainStemUp = data(:,2);
tableout.MainStemDown = data(:,3);
tableout.TribUp = data(:,4);
tableout.gwn_25_n_OBJECTID = data(:,5);
tableout.MainPolygOBJECTID = data(:,6);
tableout.TribPolygOBJECTID = data(:,7);
tableout.MainReachOBJECTID = data(:,8);
tableout.TribReachOBJECTID = data(:,9);
tableout.TribGEWISSNR = data(:,10);
tableout.MainGEWISSNR = data(:,11);
tableout.SecondMainPolygID = data(:,12);
tableout.TwoMainBasins = data(:,13);
tableout.Observations = cellVectors(:,2);
tableout(isnan(tableout.NUMERO),:) = [];

